### ISSUE TITLE
Implement OS abstraction

### ISSUE THREAD

**Issue by h33p** [memflow/memflow#10]
Currently OS is not abstracted away, thus, it is not possible to write a memflow program that is OS-agnostic.

Abstracting the OS/Kernel into some kind of trait would also simplify our CLI tool.

The plan would be to take a look at the current Win32 OS implementation, and describe it all in a OS-independent way which then can be added in the core.

The abstraction should work both with trait objects, and static compilation.

**Comment by ko1N** [comment]
OS Layers are now merged to next.
