### ISSUE TITLE
how to allocate memory for window process

### ISSUE THREAD

**Issue by shangdongfeng** [memflow/memflow#101]
Hello, I just used memflow and tested the memory read and write very well. But I have a need to apply for a piece of memory address for a program in the window of the kvm virtual machine. I don't know if this requirement can be realized with the help of memflow?

Looking forward to your reply

**Comment by emesare** [comment]
Allocating memory to a process, or otherwise, is something you must figure out yourself, there is no one size fits all, you can of course do it, it's just not something that can be easily made generic over the given `Process` interface.
