### ISSUE TITLE
An example of writing a call instruction?

### ISSUE THREAD

**Issue by Dizans** [memflow/memflow#104]
Sorry, I'm a beginner in cheating. 

When I was studying a sample project, I discovered that it runs by allocating memory and then writing binary code to the allocated memory (using [pymem](https://github.com/srounet/Pymem/blob/4d8380c2e095461783f3f5f214843c40d2ea7684/pymem/memory.py#L9)). I want to achieve the same functionality in memflow, but as a DMA, memflow does not provide, and seemingly should not provide, a memory allocation function. 

My current idea is to find an allocated but unused memory block with memflow, such as the (capacity - len) portion of a vector, and then write the binary code into that memory block to simulate the memory allocation action in the example. Is this approach feasible? How can I find such a vector? Or what should I do? I'm looking forward to receiving some advice or links to related resources. I realize that it may not be appropriate to ask this question here, and I apologize for not being able to find a better place to ask.

**Comment by h33p** [comment]
Off-topic
