### ISSUE TITLE
Enumerate process threads

### ISSUE THREAD

**Issue by JIUYUE521** [memflow/memflow#107]
The project has multiple processes with duplicate PID names. The function can be used to enumerate the number of threads in its process PID to obtain its true process PID

Similar to Windows API functions

DWORD pid = 0, cntThread = 0;
HANDLE h = CreateToolhelp32Snapshot(TH32CS_SNAPPROCESS, 0);
if (h != INVALID_HANDLE_VALUE)
{

	PROCESSENTRY32 Info = { 0 };
	Info.dwSize = sizeof(PROCESSENTRY32);
	BOOL bRet = FALSE;
	bRet = Process32First(h, &Info);
	while (bRet)
	{
		if (_stricmp("360ChromeX.exe", Info.szExeFile) == 0)
		{
			if (Info.cntThreads > cntThread)
			{
				cntThread = Info.cntThreads;
				pid = Info.th32ProcessID;
			}
		}
		bRet = Process32Next(h, &Info);
	}
	CloseHandle(h);

	if (cntThread > 100)
		return pid;
	else
		return 0;
}

return 0;

![444](https://github.com/memflow/memflow-kvm/assets/143420698/6fb95d2b-ee1e-4ef7-8e44-fcaa8467c4f7)

**Comment by h33p** [comment]
Currently, memflow does not have such provisions. This would first need to be implemented in `memflow-win32`, or `memflow-native`, and then exposed within the `Process` trait.

**Comment by JIUYUE521** [comment]
Thank you for your answer. That's true. I couldn't find a suitable function to use it

Will such function calls be added later?

**Comment by JIUYUE521** [comment]
The function of memflow-win32 can only be a single process PID

No more process PID instances or thread count

**Comment by h33p** [comment]
This would be added later, but it currently is not high on the priority list.

**Comment by JIUYUE521** [comment]
This is very useful. If there are multiple process PID's, you cannot find the process PID thread you need

Thank you for adding the use of this function!

**Comment by JIUYUE521** [comment]
Mr. H33p, I love you. If there is a chance for you to come to Shanghai, China, I will treat you to hot pot!

**Comment by ko1N** [comment]
Looking at your original question and the example code this seems more like you want to enumerate all processes with a specific name? Enumerating processes (unlike Enumerating Threads) currently already exists.

To list all processes and their pids you can take a look at our [process_list example](https://github.com/memflow/memflow/blob/main/memflow/examples/process_list.rs#L15). This way you could filter for specific process names.

You can try running the examples like mentioned in the quick start guide: https://memflow.io/quick_start/

Actual thread enumeration might be implemented at a later stage (maybe in 0.3?)
Hope this helps 👍

**Comment by JIUYUE521** [comment]
Mr. Ko1N, thank you for your answer. I will read the examples you provided

You did understand what I was saying

**Comment by ko1N** [comment]
I hope the examples helped. I will close this issue as stale now. If you need more assistance feel free to open another issue. 👍
