### ISSUE TITLE
memflow-cli not present anymore

### ISSUE THREAD

**Issue by GanbaruTobi** [memflow/memflow#110]
in the linked tutorials it is stated to install the memflow-cli with:

cargo install --git https://github.com/memflow/memflow-cli/ --branch dev --force memflow-cli

It seems that this does not exist anymore and it would be nice to comment on how to install this cli or the new equivalent.

Thank you

**Comment by ko1N** [comment]
Hey there, thanks for the issue! I will remove the old tutorial series from the readme as theyre really only valid for 0.1. As a replacement for the old CLI we now have https://github.com/memflow/cloudflow - Although its very early in development still and potentially lacking quite a couple features. Maybe you can elaborate a bit more on the use case you have for it?
