### ISSUE TITLE
Building memflow-native from development fails with memflowup

### ISSUE THREAD

**Issue by GanbaruTobi** [memflow/memflow#111]
This is the result from memflowup interactive and installing memflow-native with the development option, like showing in the docs at https://memflow.io/quick_start/

![grafik](https://github.com/memflow/memflow/assets/15239745/02370090-03b3-432c-ab06-6ecd8005533a)

**Comment by GanbaruTobi** [comment]
Using stable also doesnt work:
![grafik](https://github.com/memflow/memflow/assets/15239745/6a58e38b-8f86-4dfb-879c-c2346108dbbc)

**Comment by danielnehrig** [comment]
There are also issues on CI with 1.73
locally for me on 1.76 i can build latest native main just fine maybe try upgrading for the mean time while stuff is fixed
or revert back to an older commit of the repo

**Comment by GanbaruTobi** [comment]
Locally i run rustc with 1.76.0 if thats what you are referring to. memflow seems to hardcode to 1.74.0 in its cargo.toml, but memflowup is not and thats what I am using.

**Comment by ko1N** [comment]
Thanks for the heads up! I reverted to the older procfs version to fix this. However we are waiting for https://github.com/m4b/goblin/pull/386 to properly re-release memflow-native and fix it properly in memflowup. Additionally memflow-pcileech needs to be fixed in memflowup, too.

**Comment by ko1N** [comment]
I worked on the new memflowup release in the last couple weeks specifically for binary builds. If you wanna give it a shot, we already have release artifacts for memflow-native added. We still wait for the goblin merge to provide a proper crates.io release.

To give it a shot:
```bash
# install the current git version of memflowup:
cargo install --git https://github.com/memflow/memflowup

# query available artifacts of memflow-native:
memflowup --skip-version-check registry ls native

# pull the latest
memflowup --skip-version-check pull native

# alternatively install from source:
memflowup --skip-version-check build https://github.com/memflow/memflow-native
```

Let me know if this works for you. Once we have some more testing done we are fully releasing the new memflowup and then you can omit the `--skip-version-check` flag.

Hope this helps :)

**Comment by GanbaruTobi** [comment]
# pull the latest
memflowup --skip-version-check pull native

On Linux:
![grafik](https://github.com/memflow/memflow/assets/15239745/b9dfabfd-d4d9-4326-868f-4837490b447a)

On Windows:
![grafik](https://github.com/memflow/memflow/assets/15239745/7f6889aa-b2fc-44af-992c-7c5cee019a14)

Building from source worked on both systems
