### ISSUE TITLE
Listing Modules with memflow stable breaks

### ISSUE THREAD

**Issue by GanbaruTobi** [memflow/memflow#112]
The output of module_list hangs in the process of retrieval on my Windows 11 VM. Connector is qemu.

Result:
![grafik](https://github.com/memflow/memflow/assets/15239745/72bbefd8-2129-415d-864a-c2214a07a684)

Here is the debug log for some context:
![grafik](https://github.com/memflow/memflow/assets/15239745/a3343b63-9733-453d-ae27-ff0e01d97330)
And the trace
![grafik](https://github.com/memflow/memflow/assets/15239745/2557fc94-c9a3-4767-8c1a-245a0a180a54)

my code:
```rust
pub fn main() -> Result<()> {
    let matches = parse_args();
    let (chain, module_name) = extract_args(&matches)?;

    // create inventory + connector
    let inventory = Inventory::scan();
    let connector = inventory.builder().connector_chain(chain).build()?;

    let mut os = Win32Kernel::builder(connector)
        .build_default_caches()
        .build()
        .expect("unable to initialize memflow-win32");
    
    
    let module_list = os.module_list();

    info!("{:>5} {:>10} {:^32} {:<}", "ADDR", "BASE", "NAME", "PATH");
    for m in module_list.unwrap(){
        info!("{:>5} {:^16} {:^32} {}", m.address, m.base, m.name, m.path); 
        }
    }

    Ok(())
}
```

**Comment by ko1N** [comment]
That seems odd. Does it hang while printing the module list itself? Because memflow isn't involved at this point anymore. `module_list()` will just return the list and you just iterate the `Vec<>` containing all modules. Could you try to attach a debugger and step into the loop and see if `name` or `path` could be bogus / contain broken strings?

**Comment by GanbaruTobi** [comment]
I actually don't know how to make lldb work with the code. I am new to rust and I just modified an example. I tried lldb in VS Code, but since I only know configs that rebuild the binary before debugging I cannot run it bc then the permissions are missing to execute qemu.

By manually extracting the name and path before accessing the drivers space I can see that the fields are broken:

![grafik](https://github.com/memflow/memflow/assets/15239745/2de63a22-970d-4806-837a-cbd977e816f5)

**Comment by GanbaruTobi** [comment]
The error also appear while executing os.module_list() i just recognized:
![grafik](https://github.com/memflow/memflow/assets/15239745/dd3fa229-d8ec-4d8f-90c0-60fb34b56e1e)
![grafik](https://github.com/memflow/memflow/assets/15239745/3d768185-7e44-40a4-b5c3-805940cbc5b2)

**Comment by GanbaruTobi** [comment]
Okey,  this seems to be an issue in Qemu, I am sorry.
![grafik](https://github.com/memflow/memflow/assets/15239745/ea71edf7-d181-4ff9-82cd-82921b555374)
This is how the drivers look from inside the vm and it has some problem with some qemu thingy...

**Comment by ko1N** [comment]
> The error also appears while executing os.module_list() i just recognized: ![grafik](https://private-user-images.githubusercontent.com/15239745/310532403-dd3fa229-d8ec-4d8f-90c0-60fb34b56e1e.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDk3MzU0MTUsIm5iZiI6MTcwOTczNTExNSwicGF0aCI6Ii8xNTIzOTc0NS8zMTA1MzI0MDMtZGQzZmEyMjktZDhlYy00ZDhmLTkwYzAtNjBmYjM0YjU2ZTFlLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAzMDYlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMzA2VDE0MjUxNVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTJiYjVlNzUxNWI1MDQ2Mzk2ZWNhNDI0MTBlNGQ4MmQ1ZGE4NGM1NjY1YzRlMmQ0MjJjNTNkYzQ4NjliMDU2NzkmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.RXbelmEHN6kYx1DUZ07LNGgpHeFlY0LSa_sBSWgnfQU) ![grafik](https://private-user-images.githubusercontent.com/15239745/310532613-3d768185-7e44-40a4-b5c3-805940cbc5b2.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDk3MzU0MTUsIm5iZiI6MTcwOTczNTExNSwicGF0aCI6Ii8xNTIzOTc0NS8zMTA1MzI2MTMtM2Q3NjgxODUtN2U0NC00MGE0LWI1YzMtODA1OTQwY2JjNWIyLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAzMDYlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMzA2VDE0MjUxNVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTVkNzdhODcyYWQ3ZTVmYzU2NzJlODBiZTdhYjRkZTNjZDNjMTVlY2NlMGVkOWU0N2JmNmEyYjE5ZmU1NWUyZGImWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.PUs4nERen9rs6CBgZVfhq2apZZ21HtoJ0BUk8HfNRSw)

Alright, im not sure if i understand correctly but the errors you say are not unlikely to happen. You cannot guarantee that all required data is in memory at all times. The OS will page out memory to disk to safe resources in RAM. When this happens on one of those strings you are likely seeing that message. It's nothing too worry about though, it might just mean that it might not show all information for all modules. We are using a best-guess approach and try to give you as much info as possible.

When reading your issue first i thought you meant the program "crashes" or "hangs" but it seems to be working properly.

Theres certain windows tricks you can do to reduce pageouts of memory however.



> Okey, this seems to be an issue in Qemu, I am sorry. ![grafik](https://private-user-images.githubusercontent.com/15239745/310535408-ea71edf7-d181-4ff9-82cd-82921b555374.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDk3MzU3NzIsIm5iZiI6MTcwOTczNTQ3MiwicGF0aCI6Ii8xNTIzOTc0NS8zMTA1MzU0MDgtZWE3MWVkZjctZDE4MS00ZmY5LTgyY2QtODI5MjFiNTU1Mzc0LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAzMDYlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMzA2VDE0MzExMlomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTBkODhjZjgyM2Y0NGI0ZDg3ZGI2Njg0NGFhMDVhM2U1ZmQ3ZTA4NWEyYWY3ZjEwMTdjNWEwNjljNTAwMGJlYjUmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.jLUv2xF2Q386wfhJjH5Azg4cqM3I9mORf-pziptTWtk) This is how the drivers look from inside the vm and it has some problem with some qemu thingy...

What do you mean exactly here? If all drivers are installed in the VM doesnt matter for memflow itself.

**Comment by GanbaruTobi** [comment]
It seems you are right, after fixing the driver issue the problem still persists. This means os.module_list() will fail randomly while parsing because of paged out memory?
It surprises me that the kernel is even able to page out the information of where modules are located, seems rather important. 

After disabling the page file the problem still persists. I guess i will have to just try/catch/ignore there errors?

**Comment by ko1N** [comment]
It's not out of the ordinary that there might be entries that are not fully populated. We do not apply any filtering to the module_list output. You could however simply filter out empty names if your use case needs that.
