### ISSUE TITLE
Unable to load native connector on windows.

### ISSUE THREAD

**Issue by GanbaruTobi** [memflow/memflow#113]
On windows it seems that neither memflow 0.2.1 or 0.2.0 are able to load the native connector from the user/Documents/memflow/ folder or from the executeable folder. Also adding to the env path didnt make the connector available

![grafik](https://github.com/memflow/memflow/assets/15239745/825ccedd-ecd8-4dfc-8e7d-1d4b4ecdeefb)

or 

![grafik](https://github.com/memflow/memflow/assets/15239745/58b00d18-736d-4759-8c33-10b00c41e43f)

**Comment by h33p** [comment]
Native is an OS layer, not a connector. Use `--os native` (with no connector)
