### ISSUE TITLE
How to use memflow.hpp to read/write physmem?

### ISSUE THREAD

**Issue by Jotalz** [memflow/memflow#120]
I tried to implement it using the following method but with no success,I think I definitely misunderstood their usage,could you give me some guidance?Thank you very much!

```
int physicalMemoryRW(const char *proc_name)
{
    int ret;
    if (!(ret = os.process_by_name(CSliceRef<uint8_t>(proc_name), &proc.hProcess)))
    {
        const ProcessInfo *info = proc.hProcess.info();
        PhysicalAddress phy_address;
        proc.hProcess.virt_to_phys(info->address, &phy_address);  // Convert from virtual address to physical address

        // A custom sized area to read the address I need
        uint8_t eprocess[0x100];
        memset(eprocess, 0xff, sizeof(eprocess));

        auto physMemory = conn->phys_view();  // Get physical memory view? Not sure

        bool read_result = physMemory.read_raw_into(phy_address.address, CSliceMut<uint8_t>((char *)eprocess, sizeof(eprocess)));
        if (!read_result)
        {
            printf("Read failed!\n");
            return;
        }
        bool write_result = physMemory.write_raw(phy_address.address, CSliceRef<uint8_t>((char *)eprocess, sizeof(eprocess)));
        if (!write_result)
        {
            printf("Write failed!\n");
            return;
        }
    }
    return ret;
}
```
And a common initialization.
```
int init()
{
    inventory = mf_inventory_scan();
    if (!inventory)
    {
        mf_log_error("unable to create inventory");
        return 1;
    }
    printf("inventory initialized: %p\n", inventory);

    const char *conn_name = "kvm";
    const char *conn_arg = "";

    const char *conn2_name = "qemu";
    const char *conn2_arg = "";

    const char *os_name = "win32";
    const char *os_arg = "";
    static ConnectorInstance<> *conn = 0;
    ConnectorInstance connector;
    conn = &connector;

    if (conn)
    {
        if (mf_inventory_create_connector(inventory, conn_name, conn_arg, &connector))
        {
            printf("unable to initialize connector\n");
            mf_inventory_free(inventory);
            return 1;
        }

        printf("connector initialized: %p\n", connector.container.instance.instance);
    }

    OsInstance<> os;
    if (mf_inventory_create_os(inventory, os_name, os_arg, conn, &os))
    {
        printf("unable to initialize OS\n");
        mf_inventory_free(inventory);
        return 1;
    }

    printf("os plugin initialized: %p\n", os.container.instance.instance);
    return 0;
}
```

**Comment by sleshep** [comment]
I assume function **read_raw_into** and **write_raw** return 0 means sucesss.

**Comment by Jotalz** [comment]
> I assume function **read_raw_into** and **write_raw** return 0 means sucesss.

Yes! you are right.even if I remove the correctness verification it still doesn't work, because the key to the problem is how to read the physical memory correctly.The current approach doesn't work.

**Comment by patrickjeremic** [comment]
iirc eprocess on windows lives in the ntoskrnl virtual memory, not physical memory - when you resolve the virtual address to the physical one via the process's dtb the result might be a valid address but pointing to the wrong location. you'd need the kernel's dtb and then do a virtual read to the eprocess/kprocess address.

**Comment by ko1N** [comment]
iirc eprocess on windows lives in the ntoskrnl virtual memory, not physical memory - when you resolve the virtual address to the physical one via the process's dtb the result might be a valid address but pointing to the wrong location. you'd need the kernel's dtb and then do a virtual read to the eprocess/kprocess address.

**Comment by Jotalz** [comment]
I use memflow_qemu and memflow_win32 to connect to windows kvm, I try to read/write the physical memory of this system, in fact it has nothing to do with eprecess, it's just an example:)
In the examples [here](memflow-ffi/examples/c/phys_mem.c), I saw that reading physical memory using memflow.h.I'm wondering how this should be achieved using memflow.hpp, this is what I'm asking

**Comment by Jotalz** [comment]
> iirc eprocess on windows lives in the ntoskrnl virtual memory, not physical memory - when you resolve the virtual address to the physical one via the process's dtb the result might be a valid address but pointing to the wrong location. you'd need the kernel's dtb and then do a virtual read to the eprocess/kprocess address.

Is it possible to obtain the memory operation object of the vm system by using `auto physMemory = os->phys_view();`?
