### ISSUE TITLE
Switch back to upstream x86_64

### ISSUE THREAD

**Issue by h33p** [memflow/memflow#22]
There were portability issues with x86_64 which made us fork the crate. But now, it has been fixed in the upstream in https://github.com/rust-osdev/x86_64/pull/179. We should switch back to the upstream version.

**Comment by h33p** [comment]
This has been done in https://github.com/memflow/memflow/commit/54c889033ca0c9beffeafb83c11d57528f660127

**Comment by ko1N** [comment]
The forked repository has been archived and the crate https://crates.io/crates/x86_64_structs has been yanked.
