### ISSUE TITLE
memflow-ffi fails with "unable to get qemu memory maps"

### ISSUE THREAD

**Issue by waterbear515** [memflow/memflow#30]
Hey, thanks for all the great work on this new library! I'm coming from vmread and trying to upgrade my project to Memflow.  Unfortunately I've encountered an issue that I believe is a bug with the C bindings.

Compiling and running the examples in either memflow-ffi or memflow-win32-ffi always fails:

```
[grim@arch examples]$ ./dump_header.out qemu_procfs win10
2020-10-06 21:59:58,793 INFO  [memflow::connector::inventory] scanning "/usr/local/lib/memflow" for connectors
2020-10-06 21:59:58,793 INFO  [memflow::connector::inventory] scanning "/home/grim/.local/lib/memflow" for connectors
2020-10-06 21:59:58,793 INFO  [memflow::connector::inventory] adding connector: "/home/grim/.local/lib/memflow/libmemflow_coredump.so"
2020-10-06 21:59:58,793 INFO  [memflow::connector::inventory] adding connector: "/home/grim/.local/lib/memflow/libmemflow_qemu_procfs.so"
2020-10-06 21:59:58,793 INFO  [memflow::connector::inventory] adding connector: "/home/grim/.local/lib/memflow/libmemflow_kvm.so"
inv: 0x55e2fb63e660
2020-10-06 21:59:58,798 DEBUG [memflow::connector::inventory] connector error: unable to get qemu memory maps
2020-10-06 21:59:58,798 ERROR [memflow_ffi::util] connector error: Failed to create connector
conn: (nil)
2020-10-06 21:59:58,798 TRACE [memflow_ffi::connectors] inventory_free: 0x55e2fb63e660
```

I've verified that the non-ffi examples work fine:
```
[grim@arch memflow]$ target/release/examples/dump_offsets -c qemu_procfs -a win10
pdb_file_name = 'ntkrnlmp.pdb'
pdb_guid = '641F55C592201DCC4F59FACC72EA54DA1'
nt_major_version = 10
nt_minor_version = 0
nt_build_number = 19041
arch = 'X64'

[offsets]
list_blink = 8
eproc_link = 1096
kproc_dtb = 40
eproc_pid = 1088
eproc_name = 1448
eproc_peb = 1360
eproc_section_base = 1312
eproc_exit_status = 2004
eproc_thread_list = 1504
eproc_wow64 = 1408
kthread_teb = 240
ethread_list_entry = 1256
teb_peb = 96
teb_peb_x86 = 48

[grim@arch memflow]$ cargo run --example read_keys -- -c qemu_procfs
    Finished dev [unoptimized + debuginfo] target(s) in 0.08s
    Running `/home/grim/memflow/./runner.sh target/debug/examples/read_keys -c qemu_procfs`
space down: false
space down: false
               space down: true
                               space down: true
    space down: true
 space down: true
                  space down: true
space down: false

```

I can't seem to figure out what the issue is, but only the rust examples work. The C examples will compile, but as seen in the error above, they all error with "**unable to get qemu memory maps**". I've tried all ffi examples and they all fail with the same error. It appears that the C bindings just don't work.

**Comment by ko1N** [comment]
Thanks for checking out the project and opening the first real issue :+1: !

Did u set the ptrace permissions for the FFI binary? If you're using the current master branch there is a script that will set the appropiate permissions for the rust binaries (theres currently a tracking issue to rework those).

To let the process access the memory maps you can either just set the permissions for it like so:
```
sudo setcap 'CAP_SYS_PTRACE=ep' dump_header.out
```

Alternatively running the process through sudo should also work.

Can you check if those are set properly?

**Comment by waterbear515** [comment]
Setting the ptrace permission worked! Thank you!

Sorry that the first issue opened ended up being a non-issue, but hopefully this will help others in the future if they run into the same problem.

**Comment by ko1N** [comment]
I updated the README on the dev branch and also updated the qemu_procfs readme with an appropriate Permissions section. This should hopefully make it more clear for future users.
