### ISSUE TITLE
Add forward declare for dataview::Pod

### ISSUE THREAD

**Issue by petikk** [memflow/memflow#45]
Having a forward declaration for the `dataview::Pod` dependency would be nice to have and prevents the need to deal with mismatched versions.

**Comment by ko1N** [comment]
I pushed the changes to the `dev` branch so it should be in the next minor release.
What you now do is:
```rust
use memflow::prelude::v1::*;
```
which includes the custom Pod derive macro as well as the upstream dataview dependency.

Alternatively you can include it manually via:
```
use memflow::dataview::*;
```
Which includes the proc macro from ::memflow_derive::Pod as well as the dataview crate itself.
