### ISSUE TITLE
Derive `dataview::Pod` on `Address`

### ISSUE THREAD

**Issue by dank** [memflow/memflow#49]
I wish there was a way to read memory directly into an `Address` struct. 

I'm happy to implement this if this isn't an oversight on my end.

**Comment by ko1N** [comment]
The Address is a wrapper type that internally uses an u64. Making it Pod would cause errors when working with 32-bit targets.
Theres a few function which help to read Addresses however.

Mainly virt_read_addr32, virt_read_addr64 and virt_read_addr_arch (which takes an arch as the argument).
You can find the documentation here:
https://docs.rs/memflow/0.1.5/memflow/mem/virt_mem/trait.VirtualMemory.html#method.virt_read_addr32

For native pointer types I recommend looking into Pointer32 and Pointer64 types (which can also wrap a Pod object themselves).
You can find an example on how to use it here:
https://github.com/ko1N/csgo-internal-dumper/blob/master/src/engine/interface_manager.rs#L138

**Comment by dank** [comment]
Thank you. I must’ve missed that function.
