### ISSUE TITLE
Keyboard C++ FFI

### ISSUE THREAD

**Issue by tudou** [memflow/memflow#62]
I have tried the read-keys example and it is working great on my QEMU vm.
I am trying to do something similar in C++ but cannot seem to find any keyboard classes in either of the generated headers.

Is this something planned for in the future?

**Comment by h33p** [comment]
Yes! We have been hard at work on the 0.2 version of the library, which should fix the shortcomings of the C/C++ FFI. Everything is yet to be set in stone, but the next branch should be able to have some (although not very ergonomic) way to access keyboard:

https://github.com/memflow/memflow/blob/next/memflow/examples/keyboard.rs
https://github.com/memflow/memflow/blob/next/memflow-ffi/memflow.h

However, it's not yet set in stone, I would say a couple of months before 0.2 is out with a clean C++ wrapper.

**Comment by h33p** [comment]
If you are eager to try the next branch, I would check the keyboard vtable on [OsLayerFunctionTable](https://github.com/memflow/memflow/blob/next/memflow-ffi/memflow.h#L710) (which in itself is stored on [OsInstance](https://github.com/memflow/memflow/blob/next/memflow-ffi/memflow.h#L770) that can be created through [inventory_create_os](https://github.com/memflow/memflow/blob/next/memflow-ffi/memflow.h#L894))

**Comment by tudou** [comment]
Thank you for the fast reply, I'll be sure to check the next branch, if I encounter any issues Ill make sure to let know, and thanks for the great library.

**Comment by h33p** [comment]
No worries! And thank you :)

The main difference in 0.2 is that win32 is now a plugin like qemu-procfs. It will be necessary to put it in the same path as the connectors (and the qemu connector will need recompiling on the next branch too).
