### ISSUE TITLE
Memflow build issue: define a minimum rust version

### ISSUE THREAD

**Issue by mtarral** [memflow/memflow#71]
Hi,

It seems that memflow cannot be compiled with the current rust version of Debian sid
https://packages.debian.org/sid/cargo (0.47)

~~~
error[E0658]: const generics are unstable
   --> /root/.cargo/registry/src/github.com-1ecc6299db9ec823/dataview-0.1.2/src/lib.rs:170:27
    |
170 | unsafe impl<T: Pod, const N: usize> Pod for [T; N] {}
    |                           ^
    |
    = note: see issue #74878 <https://github.com/rust-lang/rust/issues/74878> for more information

error: aborting due to previous error

For more information about this error, try `rustc --explain E0658`.
error: could not compile `dataview`.
~~~

Do you think you could declare a minimum rust version in your README ?

Thanks !

**Comment by ko1N** [comment]
Thanks for the hint! I updated the Readme on the next branch to reflect this requirement!

https://github.com/memflow/memflow/tree/next#compilation-support
