### ISSUE TITLE
kernel_build failing when GPU passthrough to kvm

### ISSUE THREAD

**Issue by r0dw3llr** [memflow/memflow#75]
Hi,

I don't have enough ASM genius to go deeper into the issue.

Guest OS is W10, tried multiple flavors and versions.

Problem is persistent. Multiple fresh installs of Ubuntu 20.04 were attempted.

Problem does not appear when no GPU is passed to VM.

Only when a GPU is passed to VM.

Trace :  
`

__GI_raise | ../sysdeps/unix/sysv/linux/raise.c:50 | 0x7ffff7a9118b |  
-- | -- | -- | --

__GI_abort | abort.c:79 | 0x7ffff7a70859 |  

__libc_message | ../sysdeps/posix/libc_fatal.c:155 | 0x7ffff7adb3ee |  

malloc_printerr | malloc.c:5347 | 0x7ffff7ae347c |  

unlink_chunk | malloc.c:1460 | 0x7ffff7ae3acc |  

_int_realloc | malloc.c:4594 | 0x7ffff7ae70c1 |  

__GI___libc_realloc | malloc.c:3226 | 0x7ffff7ae9136 |  

alloc::alloc::realloc | /build/rustc-Nbf2Kl/rustc-1.53.0+dfsg1+llvm/library/alloc/src/alloc.rs:122 | 0x5555559b5fb0 |  

alloc::alloc::Global::grow_impl | /build/rustc-Nbf2Kl/rustc-1.53.0+dfsg1+llvm/library/alloc/src/alloc.rs:198 | 0x5555559b5fb0 |  

<alloc::alloc::Global as core::alloc::Allocator>::grow | /build/rustc-Nbf2Kl/rustc-1.53.0+dfsg1+llvm/library/alloc/src/alloc.rs:251 | 0x5555559b5fb0 |  

alloc::raw_vec::finish_grow | /build/rustc-Nbf2Kl/rustc-1.53.0+dfsg1+llvm/library/alloc/src/raw_vec.rs:496 | 0x5555559b5fb0 |  

alloc::raw_vec::RawVec<T,A>::grow_amortized | /build/rustc-Nbf2Kl/rustc-1.53.0+dfsg1+llvm/library/alloc/src/raw_vec.rs:431 | 0x5555555f71f2 |  

alloc::raw_vec::RawVec<T,A>::reserve::do_reserve_and_handle | /build/rustc-Nbf2Kl/rustc-1.53.0+dfsg1+llvm/library/alloc/src/raw_vec.rs:324 | 0x5555555f71f2 |  

alloc::raw_vec::RawVec<T,A>::reserve | /build/rustc-Nbf2Kl/rustc-1.53.0+dfsg1+llvm/library/alloc/src/raw_vec.rs:328 | 0x5555558ac0db |  

alloc::vec::Vec<T,A>::reserve | /build/rustc-Nbf2Kl/rustc-1.53.0+dfsg1+llvm/library/alloc/src/vec/mod.rs:780 | 0x5555558ac0db |  

alloc::vec::Vec<T,A>::append_elements | /build/rustc-Nbf2Kl/rustc-1.53.0+dfsg1+llvm/library/alloc/src/vec/mod.rs:1696 | 0x5555558ac0db |  

<alloc::vec::Vec<T,A>  as  alloc::vec::spec_extend::SpecExtend<&T,core::slice::iter::Iter<T>>>::spec_extend | /build/rustc-Nbf2Kl/rustc-1.53.0+dfsg1+llvm/library/alloc/src/vec/spec_extend.rs:83 | 0x5555558ac0db |  

alloc::vec::Vec<T,A>::extend_from_slice | /build/rustc-Nbf2Kl/rustc-1.53.0+dfsg1+llvm/library/alloc/src/vec/mod.rs:2119 | 0x5555558ac0db |  

std::sys_common::os_str_bytes::Buf::push_slice | library/std/src/sys_common/os_str_bytes.rs:141 | 0x5555558ac0db |  

std::ffi::os_str::OsString::push | library/std/src/ffi/os_str.rs:181 | 0x5555558ac0db |  

std::path::PathBuf::_push | library/std/src/path.rs:1203 | 0x5555558ac0db |  

std::path::PathBuf::push | library/std/src/path.rs:1174 | 0x5555558ac0db |  

std::path::Path::_join | library/std/src/path.rs:2207 | 0x5555558ac0db |  

<memflow_win32::offsets::symstore::SymbolStore as core::default::Default>::default | /build/rustc-Nbf2Kl/rustc-1.53.0+dfsg1+llvm/library/core/src/panicking.rs:143 | 0x5555556421c0 |  

kernel_build

`

**Comment by ko1N** [comment]
On what memflow version did this happen (0.1.5 or next)?
Can you provide a more sophisticated output of the exact point it failed at? On first glance this seems to fail in the SymbolStore somewhere? Maybe a debug build could be helpful.

**Comment by r0dw3llr** [comment]
Memflow 0.1.5

This trace was with the debug symbols on compile, gdb as debugger. 

Else the only output I get is :

"corrupted double linked list
Aborted"

The rust code is used as a library which is why I only see the entrypoints of the functions when kernel_build is called. (qemu_procfs)

As I said, with no GPU there is no such issue. 

Only when a GPU is passed through.

**Comment by ko1N** [comment]
`impl Default for SymbolStore {
    fn default() -> Self {
        let home_dir = home_dir().expect("unable to get home directory");
        Self {
            base_url: "https://msdl.microsoft.com/download/symbols".to_string(),
            cache_path: Some(home_dir.join(".memflow").join("cache")),
        }
    }
}
`

The only call to join happens on the users home directory which would be kinda strange if this results in a core dump. Also there's not really a difference between a VM that has a GPU attached vs one that hasn't (in terms of memflow, that is).

**Comment by r0dw3llr** [comment]
I'lll investigate it more and I'll try and get more information. Thanks for the prompt response.

**Comment by r0dw3llr** [comment]
I can't get to the bottom of it ... switched to KVM connector for now.

**Comment by EightB1ts** [comment]
I had a similar issue. I was able to resolve it by disabling resizable BAR support
