### ISSUE TITLE
How do I sponser you?

### ISSUE THREAD

**Issue by rlewkowicz** [memflow/memflow#80]
I think projects have to sign up to be sponsored. I dont see the button, I might just be dumb. Or even a venmo, btc wallet, xmr, patreon, anything. You're amazing. This project is amazing this whole eco system is amazing. Between yall and frisk you're all so stunning. I have a nerd crush.

**Comment by dankope** [comment]
@h33p is apart of the developer sponsor program, you can sponsor him [here](https://github.com/sponsors/h33p)!
