### ISSUE TITLE
Can we use this library in c++?

### ISSUE THREAD

**Issue by worthl3ss** [memflow/memflow#84]
Can we use this library in c++? I learnt a bit of cpp and I don't feel comfortable learning another language right now, is there any way we can use this in a c++ based software?

**Comment by weewoo22** [comment]
Yup, please see: [`memflow-ffi/`](https://github.com/memflow/memflow/tree/main/memflow-ffi) tree

**Comment by ko1N** [comment]
I personally also really recommend using CMake, hence we provide a simple example project: https://github.com/memflow/memflow-cmake-example

**Comment by worthl3ss** [comment]
Awesome, thanks for the responses!

**Comment by therockf** [comment]
Sorry to comment on this old issue, but I think we need some more example to use memflow-ffi , there are just few examples for C.
I have openened an issue on memflow-cmake-example repo

https://github.com/memflow/memflow-cmake-example/issues/2

Can anyone help me?
