### ISSUE TITLE
I can't PM people on github

### ISSUE THREAD

**Issue by rlewkowicz** [memflow/memflow#85]
@ko1N this is kind weird, I can't ping people on GitHub direct, ya know?

I just wanted to ask. I follow you, and you're starring and cloning repos left and right. Can I ask what you do? You're clearly brilliant, and I'm wondering if you're just tearing through all of these different spaces with ease?

**Comment by ko1N** [comment]
Hey, sorry for the late reply! Thanks for the kind words!
It's a bit odd that there's no PM functionality on GitHub but if you want to directly engage with us please feel free to join our Discord or message us on Twitter:

https://discord.gg/PTwmAyfBKF
https://twitter.com/ko1N1337
https://twitter.com/h33p_
