### ISSUE TITLE
Question: Did somebody compared performance of memflow vs libVMI?

### ISSUE THREAD

**Issue by VPaulV** [memflow/memflow#87]
Hi Guys,

By any chance did somebody compared performance of memflow vs libVMI? I.e. during the realtime guest memory parsing and patching in KVM? Process debugging, etc.

**Comment by h33p** [comment]
It appears that libVMI's memory IO functions are sequential and process one buffer at a time, while memflow processes a sequence of buffers in one go, which enables additional optimizations. For this reason, memflow should be faster in most scenarios.

**Comment by VPaulV** [comment]
Great to know thank you! I will give it a try then, I guess it is save to assume that I can get the rest of libvmi functionality with libmicrovmi?

**Comment by h33p** [comment]
Using memflow through libmicrovmi is not complete as it is out of date and does not support CPU state modification (debugging).

**Comment by ko1N** [comment]
Did u do a performance comparison yet? Can this issue be closed?

**Comment by VPaulV** [comment]
I didn't do really in-depth comparison, but in my tests memflow was significantly faster. I guess this issue can be closed.
